var language = (function(lang, $, undefined) {
	lang.english = {
		culture: "en",
		mainTitle: 'JSU Library API Reference and examples',
		inputTypeText: '<nobr>It is considered <em>inputType:text</em> any of the following DOM elements,</nobr>',
		asideTheme: 'This page was generated by <a href="https://pages.github.com" target="_blank">GitHub Pages</a> using the Architect theme by <a href="https://twitter.com/jasonlong" target="_blank">Jason Long</a>.',
		asideBlogs: 'Recomended blogs:',
		asideArticles: 'Recomended articles:',
		asidePractices: 'Tips for Good practices'
	};
	lang.spanish = {
		culture: "es",
		mainTitle: 'Documentación del API y ejemplos de JSU Library',
		inputTypeText: '<nobr>Se considera <em>inputType:text</em> a cualquiera de los siguientes elementos DOM,</nobr>',
		asideTheme: 'Esta página fue generada por <a href="https://pages.github.com" target="_blank">GitHub Pages</a> usando el tema Architect de <a href="https://twitter.com/jasonlong" target="_blank">Jason Long</a>.',
		asideBlogs: 'Blogs recomendados:',
		asideArticles: 'Artículos recomendados:',
		asidePractices: 'Tips de Buenas prácticas'
	};
	lang.set = function(idiom) {
		if (!lang[idiom]) return;
		var _lang = lang[idiom];
		$("html").attr("lang", _lang.culture);
		$("#mainTitle").text(_lang.mainTitle);
		$("#asideTheme").html(_lang.asideTheme);
		$("#asideBlogs").text(_lang.asideBlogs);
		$("#asideArticles").text(_lang.asideArticles);
		$("#asidePractices").text(_lang.asidePractices);
		$(".inputTypeText").html(_lang.inputTypeText);
	};
	return lang;
}(language || {}, jQuery));
